- hosts: localhost
  become: true

  roles:
    - alzadude.firefox-addon
    - gantsign.pin-to-launcher

  tasks:
  - include: tasks/users.yml
  - include: tasks/packages.yml
  - include: tasks/cron.yml
#  - include: tasks/dock.yml
#  - include: tasks/config.yml
